### ISSUE TITLE
References with label in another file

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/hyperclick-latex#4]
When I click in `example1.tex` on a reference `\ref{example}` defined by a label in `example2.tex` file, I obtain the following message:

> Label declaration for reference example not found

I guess it is, either a bug or something not possible with this package. In the latter case, it could be a new feature and if it impossible, may be a message could be added to suggest that the label may be in another file ?

**Comment by Aerijo** [comment]
I can do it, by searching from the root file for the first instance of `\label{...}`. Technically, this _could_ result in a wrong match, as labels can be repositioned by using the same one in another place. However, in practice, it would be OK to do this as repositioning labels sounds like a very bad idea.

The reason I didn't support it initially was that a file can be `\input` into arbitrary places, and it is impossible to find every place it is added to. However, if the file uses the `root` magic comment, it should work to run a search from there.

I can't say when I'll get this done. I'll be working on `language-latex2e` tomorrow (hopefully getting bibtex syntax highlighting working).

**Comment by PierreMarchand20** [comment]
Quick question, if I have a `root.tex`, `example1.tex` and `example2.tex`, and I reference in `example1.tex` a label defined in `example2.tex`, would it work too ? I guess not

**Comment by Aerijo** [comment]
If I program it right it would work :)

**Comment by PierreMarchand20** [comment]
Nice :-) 

Unrelated question, I thought you were working on `language-latex` now, but you are still working on `language-latex2e` ? I ask this question because I am using `language-latex` but there have been no update for a while, so if you are maintaining your package, I could switch to `language-latex2e`.

**Comment by Aerijo** [comment]
Right now I'm working on my packages. I still watch `language-latex`, and will do something if the issue is a simple / easy one to fix, but I put most of my effort into `language-latex2e` and my others. The owner of the repo hasn't done anything for over a year, so yudai-nkt appears to be the de facto maintainer.

My package itself is completely written from scratch, with `language-latex` only being used as a guide for some scope names and also (right now) the table and reference patterns are taken from it. Although I have commit access to `language-latex`, I work on mine because I'm unsure on what would be considered worth adding, and don't want to stuff it up for 200,000 people (that, and the repo for language-latex is so disorganised it hurts to read).

It's easier to be the owner of the repo, and have room to experiment with things you think would be nice. I think that the feature set is at least on par with `language-latex` though, so there should be no missing things you would expect (except snippets; I don't have any of them, and are something I'd like to see removed from `language-latex`).

So yes, you could probably switch to `language-latex2e`. There will be packages that will not activate, as explained in my gist, so raise an issue if this happens. I will also try to fix any other issues, or add any features you ask for. Unfortunately, even though it was the first of my packages, grammar rules are still the most difficult to write. Even now, I'm still learning how they fit together. I may even have to write a new gist, just so I can remind myself on what I already know.

Plus I'm looking at only another week or two of this level of activity. When university starts, I won't have as much time as I do now, so I'm making the most of it to get the feature set in everything to a good level.

**Comment by PierreMarchand20** [comment]
Ok, thank you for your answer and for making all these nice packages available !

**Comment by Aerijo** [comment]
@PierreMarchand20 Well, that took longer than I expected. It should search the current file for the label, and if that fails it will recursively search from the root document for the first instance of the label.

This doesn't exactly match LaTeX behaviour, but should be fine so long as you don't reuse label names in a project (which sounds like a bad idea).

**Comment by PierreMarchand20** [comment]
Ok, I tried with `hyperclick-latex` 0.2.0 and it did not work for me :-/

**Comment by Aerijo** [comment]
@PierreMarchand20 What happened?

**Comment by PierreMarchand20** [comment]
Same as before, it do not find it with the same message. I can try to do a minimal example if you want to.

**Comment by Aerijo** [comment]
Yes please.

**Comment by Aerijo** [comment]
Is the label declared on a file that is inputted after the ref? I just got the error when I try this.

**Comment by PierreMarchand20** [comment]
No, the label is declared before the ref.

**Comment by Aerijo** [comment]
Nevermind, I just realised I was using the wrong ref (so it works even better for me :)

What does your document structure look like?

**Comment by PierreMarchand20** [comment]
I can send you an example, how can I send it to you ?

**Comment by Aerijo** [comment]
I've made a temporary email

9w802o+gmaen69tjf9g@sharklasers.com

**Comment by Aerijo** [comment]
Got it. hang on.

**Comment by PierreMarchand20** [comment]
Ok, thank you !

**Comment by Aerijo** [comment]
Oh sorry, it seems I haven't fully supported `include` statements. Won't be long, I just need to parse the file path and add an extension if necessary.

**Comment by Aerijo** [comment]
@PierreMarchand20 OK, I've released a patch that works with the example you sent me.

It still won't work if you have multiple file paths in an `include` command, but I'll deal with that some other time.

**Comment by PierreMarchand20** [comment]
It works for me 👍  thank you very much ! (I let you close the issue in case you want to keep it as a reminder for the `include` command with multiple file paths)
